### ISSUE TITLE
Wrong version for conditional compilation

### ISSUE THREAD

**Issue by wadealer** [coolsoftware/VHashedStringList#2]
Последний комит ломает сборку на старых версиях, т.к. даже в 2007 еще не было OwnsObjects в стринглисте. В XE уже точно есть. Т.е. это свойство появилось где-то между 2007 и ХЕ. Нужно переделать проверку так, чтобы проверялась не только 7, но и все версии до XE (или может 2009-2010).

**Comment by coolsoftware** [comment]
Сделал проверку версий до 2009

**Comment by wadealer** [comment]
[DCC Error] VHashedStringList.pas(21): E2029 $IFEND expected but $ENDIF found

**Comment by coolsoftware** [comment]
Какая версия Delphi

**Comment by wadealer** [comment]
Проверил на 2007 и на ХЕ. Одинаковая ошибка.

**Comment by coolsoftware** [comment]
У меня нет XE, на Berlin $ENDIF работает.  $IFEND тоже работает. Поменял на него - проверяйте.

**Comment by wadealer** [comment]
Все хорошо, спасибо.
